[package]
name = "zing-cmd"
version = "0.2.0"
authors = ["Aske Simon Christensen <askesc@gmail.com>"]
edition = "2021"
build = "build.rs"

[dependencies]
chrono = "0.4.11"
clap = "2.33.0"
hound = "3.4.0"
notify = "4.0.15"
rodio = "0.11.0"

ir = { path = "../ir" }
zing = { path = "../zing" }

[build-dependencies]
nasm-rs = "= 0.1.3"
